<a href="https://colab.research.google.com/github/kgpark88/nlp/blob/main/003_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

     |████████████████████████████████| 1.1MB 7.6MB/s 
     |████████████████████████████████| 3.0MB 37.5MB/s 
     |████████████████████████████████| 1.1MB 40.3MB/s 
     |████████████████████████████████| 890kB 37.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=fcbd7cb36aa723907a48730c524a7a58194c9ccbed440f69a78ca4ba18461d51
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [3]:
import torch
from transformers import BertModel, BertTokenizer

### Pre trained bert 불러오기

In [4]:
model = BertModel.from_pretrained('bert-base-uncased')

### tokenizer 불러오기

In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

### tokenizer로 자연어 문장 인코딩

In [6]:
torch.tensor(tokenizer.encode("Hello, I like coffee"))

tensor([ 101, 7592, 1010, 1045, 2066, 4157,  102])

In [ ]:
# [cls], [sep] 등의 special_tokens를 제외하고 싶은 경우 : add_special_tokens=False로 두자
torch.tensor(tokenizer.encode("Hello, I like coffee", add_special_tokens=False))

tensor([7592, 1010, 1045, 2066, 4157])

In [7]:
# encoding 된 token을 model에 넣으면 각 단어의 representation을 출력
tokens = torch.tensor(tokenizer.encode("Hello, I like coffee")).view(1, -1)
tokens

tensor([[ 101, 7592, 1010, 1045, 2066, 4157,  102]])

In [ ]:
# model(tokens)[0] : 각 단어의 representation
# shape = (1, 7, 768), 1 : batch_size / 7 : token 개수 / 768 : embedding의 차원
representations = model(tokens)[0]
representations.shape

torch.Size([1, 7, 768])

# KoBert, 한국어 BERT 예제

### beomi/kcbert-base
https://github.com/Beomi/KcBERT

In [8]:
from transformers import AutoTokenizer, AutoModelWithLMHead

tokenizer = BertTokenizer.from_pretrained("beomi/kcbert-base")
model = BertModel.from_pretrained("beomi/kcbert-base")

tokens = tokenizer.encode('안녕? 난 커피를 좋아해')
for token in tokens:
    print(tokenizer.decode(token))


[ C L S ]
안 녕
?
난
커 피
# # 를
좋 아
# # 해
[ S E P ]


### monologg/kobert
https://github.com/SKTBrain/KoBERT

In [30]:
!pip install torch 
!pip install mxnet 
!pip install gluonnlp 
!pip install sentencepiece 
!pip install onnxruntime
!pip install kobert-transformers

In [32]:
import torch
from kobert.pytorch_kobert import get_pytorch_kobert_model

input_ids = torch.LongTensor([[31, 51, 99], [15, 5, 0]])
input_mask = torch.LongTensor([[1, 1, 1], [1, 1, 0]])
token_type_ids = torch.LongTensor([[0, 0, 1], [0, 1, 0]])

model, vocab  = get_pytorch_kobert_model()
sequence_output, pooled_output = model(input_ids, input_mask, token_type_ids)
pooled_output.shape

ModuleNotFoundError: ignored

### T5
http://dsba.korea.ac.kr/seminar/?mod=document&uid=247

In [ ]:
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained('t5-large')
model = T5ForConditionalGeneration.from_pretrained('t5-large')

txt = "I <extra_id_0> school. </s>"
tokenized_txt = tokenizer(txt, return_tensors='pt')

generated_txt = model.generate(tokenized_txt['input_ids'],
                               max_length=10,
                               do_sample=True,
                               top_p=0.95,
                               temperature=0.95)

In [35]:
print(tokenizer.decode(generated_txt.squeeze()))

<extra_id_0> would be<extra_id_1>
